#!/usr/bin/env ruby
# copy this file to .git/hooks/ to automatically strip spaces from the end of
# lines and add newlines to the ends of files as necessary

filetypes = %w(
  builder
  conf
  css
  erb
  haml
  html
  js
  json
  rake
  rb
  rhtml
  rxml
  scss
  txt
  xml
  yaml
  yml
)

paths = %w(
  app
  config
  db/migrate
  lib
  public
  test
)

filetype_regexp = /\.(#{filetypes.join('|')})$/
paths_regexp = /^tapjoyads\/(#{paths.join('|')})/

files = `git diff-index --name-status --cached HEAD | grep -v ^D | cut -c3-`
files.each do |f|

  # Only examine known text files
  if f =~ filetype_regexp && f =~ paths_regexp

    # Add a linebreak to the end of the file if it doesn't have one
    if `tail -c1 #{f}` != "\n"
      `echo >> #{f}`
      #`git add #{f}`
    end

    # Remove trailing whitespace if it exists
    if `grep -q "[[:blank:]]$" #{f}`
      # sed command works differently on Mac than on Linux
      if `uname` =~ /Darwin/
        `sed -i "" -e $'s/[ \t]*$//g' #{f}`
      elsif `uname` =~ /Linux/
        `sed -i -e 's/[ \t]*$//g' #{f}`
      end
      `git add #{f}`
    end
  end
end
