development:
  aws_access_key_id: 1A3R3ANTXCET9AE95VG2
  aws_secret_access_key: KNRjoeVhTRWJf4l84xgzh7Y2DNXmJo+wbAVStQLq
  salt: dev_salt
  port: 8888

test:
  aws_access_key_id: 1A3R3ANTXCET9AE95VG2
  aws_secret_access_key: KNRjoeVhTRWJf4l84xgzh7Y2DNXmJo+wbAVStQLq
  salt: test_salt
  port: 8888

production:
  aws_access_key_id: 1A3R3ANTXCET9AE95VG2
  aws_secret_access_key: KNRjoeVhTRWJf4l84xgzh7Y2DNXmJo+wbAVStQLq
  salt: prod_salt
  port: 8888
