#
# broker.yml
#
# Simple yaml file for the env specific configuration of the broker connections.
# See the wiki for more information: http://code.google.com/p/activemessaging/wiki/Configuration
#
development:
    #################################
    # Amazon SQS Adapter Properties #
    #################################
    adapter: asqs
    access_key_id: 1A3R3ANTXCET9AE95VG2
    secret_access_key: KNRjoeVhTRWJf4l84xgzh7Y2DNXmJo+wbAVStQLq
    aws_version: 2009-02-01

    ## properties below are all defaults for this adapter
    # host: queue.amazonaws.com
    # port: 80
    # reliable: true
    # reconnectDelay: 5
    # aws_version: 2006-04-01 
    # content_type: text/plain
    # poll_interval: 1
    # cache_queue_list: true
    
test:
    adapter: asqs
    access_key_id: 1A3R3ANTXCET9AE95VG2
    secret_access_key: KNRjoeVhTRWJf4l84xgzh7Y2DNXmJo+wbAVStQLq
    aws_version: 2009-02-01

production:
    adapter: asqs
    access_key_id: 1A3R3ANTXCET9AE95VG2
    secret_access_key: KNRjoeVhTRWJf4l84xgzh7Y2DNXmJo+wbAVStQLq
    aws_version: 2009-02-01

