test:
  notifications_secret: kHm0AdTlVVzmzTkLd
  url: http://localhost:5000

development:
  notifications_secret: kHm0AdTlVVzmzTkLd
  url: http://localhost:5000

staging:
  notifications_secret: kHm0AdTlVVzmzTkLd
  url: qa.notifications.tapjoy.com

production:
  notifications_secret: kHm0AdTlVVzmzTkLd
  url: notifications.tapjoy.com