test:
  notifications_secret: kHm0AdTlVVzmzTkLd
  url: http://localhost:5000

development:
  notifications_secret: kHm0AdTlVVzmzTkLd
  url: http://localhost:5000

staging:
  notifications_secret: kHm0AdTlVVzmzTkLd
  url: http://notifications.tapjoy.com

production:
  notifications_secret: kHm0AdTlVVzmzTkLd
  url: http://notifications.tapjoy.com
