production:
    user: tapjoyprod
    passwd: b4%6GbMv
test:
    user: tapjoydev
    passwd: emailthebits
development:
    user: tapjoydev
    passwd: emailthebits
staging:
    user: tapjoydev
    passwd: emailthebits
