#!/usr/bin/env ruby

# Runs a command on all specified servers.
# Usage: cloudrun <server-group> "<command>" [<user>]
#   where <server-group> is the same server group as specified in ec2servers
#   <command> is the command to run, it must be surrounded by quotes if it contains spaces.
#   <user> is the user to run as. If not specified, the user will be webuser.
#
# For example:
#   cloudrun webserver "apachectl restart" root
#   This will restart apache on all serves in the 'webserver' security group.

server_list = `script/ec2servers #{ARGV.first}`.split("\n")
command = ARGV[1]
user = ARGV[2] || 'webuser'

# Add servers to ~/.ssh/known_hosts, so that ssh does not prompt you to type 'yes'.
f = open(File.expand_path('~/.ssh/known_hosts'), 'r')
file_content = ''
f.each do |line|
  file_content += line
end
f = open(File.expand_path('~/.ssh/known_hosts'), 'a')
server_list.each do |s|
  unless file_content.include?(s)
    puts "Adding #{s} to known_hosts"
    f.puts "#{s} ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEApZ4yGm+pCsxG/jyPfhn0Qqar0b2oA2eGgCGfcR9J1zMhcqoHUh" +
           "8/2IVpAKsPzPL9UFcpo5dYCFzm2EHwmj6x8ervGIEgoicQ4HlmIGTLEWIo2xTyYdcKw/Bg1lKC9ZKBUAr8iyfXJJVs+" +
           "4LiTUeKfZCtD31u0X+yfYjg5S3AwlWSrCApLJCOGuYHUG9TV0F480GThcZfo5FkQaoR6MnYD6NkpZ0Jmf9f/iXsdLc1" +
           "oHTcwNoePbsn8zqQ/B1vwgVKYfcKMKYRiIRqOYn06kUJn+pHzqQzpRl2xRHbpFbViIiWt3B8OX9+eftdJT5rHUBJs4Y" +
           "9YBjpT13lnvcj8gs60Q=="
  end
end
f.close

puts "Servers to run on: "
puts server_list
puts "User: #{user}"
puts "Command: #{command}"
print "Run command? [y/N] "
answer = STDIN.gets
if !/^y/i.match(answer)
  exit
end


thread_list = []

server_list.each do |s|
  thread = Thread.new do
    puts "Running on #{s}",
        `ssh #{user}@#{s} '#{command}'`,
        "\n"
  end
  thread_list.push(thread)
end

thread_list.each do |thread|
  thread.join
end
