#!/usr/bin/env ruby

# Logs in on all specified servers.
# Usage: cloudlogin <server-group>
#   where <server-group> is the same server group as specified in ec2servers

server_list = `script/ec2servers #{ARGV.first}`.split("\n")

server_num = (ARGV[1] || 0).to_i

server = server_list[server_num]

user = ARGV[2] || 'webuser'

puts "#{server_list.length} total servers:"
server_list.each_index do |i|
  puts "#{i}. #{server_list[i]}"
end
puts "Connecting to server #{server_num} as #{user}"
system "ssh #{user}@#{server}"