#!/usr/bin/env ruby

require 'yaml'

VERSION_FILENAME = '../server/version.yaml'
current_tag = YAML::load(File.open(VERSION_FILENAME))["current"]
if `uname` =~ /Darwin/
  command = "open"
elsif `uname` =~ /Linux/
  command = "xdg-open"
end
system("#{command} https://github.com/Tapjoy/tapjoyserver/compare/#{current_tag}...master")
