#!/usr/bin/env ruby

require 'yaml'

VERSION_FILENAME = '../server/version.yaml'
current_tag = YAML::load(File.open(VERSION_FILENAME))["current"]
system("open https://github.com/Tapjoy/tapjoyserver/compare/#{current_tag}...master")
