#!/usr/bin/env ruby

# A script that will run when a new ec2 instance is brought up.
# This script will run as root.
# This script depends on rails, so it must be run using script/runner. E.g.:
#  script/runner script/configure_server

require 'base64'

`mkdir -p /mnt/log/httpd`
`mkdir -p /mnt/log/rails`
`chown -R webuser.webuser /mnt/log`

version = ENV['prod_version']
run_mode = 'production'

type = Base64::decode64(DownloadContent::download_content('http://169.254.169.254/1.0/user-data'))
puts "Server type: #{type}"
if type == 'testserver'
  version = ENV['test_version']
  run_mode = 'test'
end

`su - webuser -c 'cd tapjoyads && svn switch https://tapjoy.unfuddle.com/svn/tapjoy_tapjoyads/deploy/#{version}/tapjoyads'`

`su webuser -c 'memcached -d -m 256'`

`apachectl start`

load File.expand_path("#{RAILS_ROOT}/app/jobs/register_servers_job.rb")
RegisterServersJob.new.run(run_mode)
