#!/usr/bin/env ruby

# Deploys to amazon windows servers.

puts "WINDOWS deploy"
server_list = server_list = `script/ec2servers winwebserver`.split("\n")

puts "Servers to push to:"
puts server_list

print "Deploy? [y/N] "
answer = STDIN.gets
if !/^y/i.match(answer)
  exit
end

thread_list = []

server_list.each do |s|
  thread = Thread.new do
    # Using the stricthostkeychecking=no option, which is not the best security-wise, but
    # it stops the 'yes/no' prompt. The more secure solution can be seen in the deploy
    # script, which adds the known host key identification to known_hosts file. This
    # doesn't work for windows though, because the host key changes for every instance of
    # windows, and therefore cannot be known ahead of time.
    puts "Deploying on #{s}",
        `ssh -o stricthostkeychecking=no root@#{s} ''/home/administrator/upSource.bat''`,
        "Done deploying on #{s}\n\n"
  end
  thread_list.push(thread)
end

thread_list.each do |thread|
  thread.join
end

puts "Done deploying"
