#!/usr/bin/env ruby

include Ec2Helper

if ARGV.first == 'production'
  puts "PRODUCTION deploy"
  server_list = get_dns_names('mc')
  rails_mode = 'production'
  version = ENV['prod_version']
else
  puts "TESTING deploy"
  server_list = get_dns_names('testserver')
  rails_mode = 'test'
  version = ENV['test_version']
end

puts "Servers to push to:"
puts server_list

puts "\nUpdating local svn"
puts `svn update`
#svn_info = `svn info`
#svn_rev = svn_info.match(/\nRevision: (\d*)/)[1]
print "Deploy version #{version}? [y/N] "
answer = STDIN.gets
if !/^y/i.match(answer)
  exit
end

server_list.each do |s|
  puts "Deploying on #{s}"
  
  puts `ssh webuser@#{s} 'cd tapjoyads/server && svn update && ./deploy.rb'`
  
  puts "Done deploying on #{s}\n\n"
end

puts "Done deploying"