#!/usr/bin/env ruby

# Returns a list of ec2 servers.
# Usage: ec2servers <server-group>
#   where <server-group> is one of: prod, test or all

require 'yaml'
require 'rubygems'
require 'right_aws'

def get_dns_names(group_id = nil)
  get_server_field(:dns_name, group_id)
end

def get_server_field(field_name, group_id)
  ec2 = RightAws::Ec2.new(nil, nil, :logger => Logger.new(STDERR))

  instances = ec2.describe_instances
  dns_names = []

  instances.each do |instance|
    if instance[:aws_state] == 'running' and instance[:aws_groups].include?(group_id)
      dns_names.push(instance[field_name])
    end
  end

  return dns_names
end

amazon = YAML::load_file('config/amazon.yaml')

ENV['AWS_ACCESS_KEY_ID'] = amazon['main']['access_key_id']
ENV['AWS_SECRET_ACCESS_KEY'] = amazon['main']['secret_access_key']

groups = ARGV.first.split

groups.each do |group|
  servers = get_dns_names(group)

  servers.each do |server|
    puts server
  end
end
