#!/usr/bin/env ruby

# Returns a list of ec2 servers.
# Usage: ec2servers <server-group>
#   where <server-group> is one of: prod, test or all

require 'yaml'
require 'rubygems'
require 'AWS'

amazon = YAML::load_file('config/amazon.yaml')

ENV['AWS_ACCESS_KEY_ID'] = amazon['main']['access_key_id']
ENV['AWS_SECRET_ACCESS_KEY'] = amazon['main']['secret_access_key']

load 'app/helpers/ec2_helper.rb'
include Ec2Helper

servers = get_dns_names(ARGV.first)

servers.each do |server|
  puts server
end
