#!/usr/bin/env ruby

# Restarts everything.
# This script depends on rails, so it must be run using script/runner.

rails_mode = ARGV.first || "development"
unless ["development", "test", "production"].include?(rails_mode)
  raise "Unknown rails environment '#{rails_mode}'.  (Choose 'development', 'test' or 'production')"
end

puts "Stopping poller"
`script/poller stop`
puts "Stopping jobs"
`script/jobs stop`
puts "Restarting apache"
`touch tmp/restart.txt`
puts "Deleting /var/tmp/ruby-uuid"
`rm /var/tmp/ruby-uuid`
puts "Starting jobs"
`script/jobs start -- #{rails_mode}`
puts "Starting poller"
`script/poller start -- #{rails_mode}`

load File.expand_path("#{RAILS_ROOT}/app/jobs/register_servers_job.rb")
RegisterServersJob.new.run(rails_mode)
