#!/usr/bin/env ruby

# Restarts everything.

require 'rubygems'
require 'patron'

rails_mode = ARGV.first || "development"
unless ["development", "test", "production"].include?(rails_mode)
  raise "Unknown rails environment '#{rails_mode}'.  (Choose 'development', 'test' or 'production')"
end

puts "Stopping poller"
`script/poller stop`
puts "Stopping jobs"
`script/jobs stop`
puts "Restarting apache"
`touch tmp/restart.txt`
puts "Starting jobs"
`script/jobs start -- #{rails_mode}`
puts "Starting poller"
`script/poller start -- #{rails_mode}`

# Call the register_servers job on all machines.
port = '9898'
server_list = case rails_mode
when 'production'
  `script/ec2servers mc`.split("\n")
when 'test'
  `script/ec2servers mc`.split("\n")
else
  port = '3000'
  ['http://localhost:3000']
end

server_list.each do |server|
  sess = Patron::Session.new
  sess.base_url = "#{server}:#{port}"
  sess.timeout = 60
  sess.username = 'internal'
  sess.password = 'r3sU0oQav2Nl'
  sess.auth_type = :digest

  sess.get("/job/register_servers")
end
