#!/usr/bin/env ruby

# Restarts everything.

rails_mode = ARGV.first || "development"
unless ["development", "test", "production"].include?(rails_mode)
  raise "Unknown rails environment '#{rails_mode}'.  (Choose 'development', 'test' or 'production')"
end

machine_type = `server/server_type.rb`

puts "Stopping jobs"
`script/jobs stop`

puts "Killing remaining jobs"
`server/kill_all.rb jobs`
`server/kill_all.rb poller`

puts "Restarting apache"
`touch tmp/restart.txt`

if machine_type == 'jobs' or machine_type == 'masterjobs'
  puts "Starting jobs"
  `script/jobs start -- #{rails_mode}`
end
