development:
  adapter: mysql
  database: tapjoy_db
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>
  username: root
  password:
  reconnect: true

test:
  adapter: mysql
  database: tapjoy_db_test
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>
  username: root
  password:
  reconnect: true

staging:
  adapter: mysql
  database: tapjoy_db_staging
  host: tapjoy-rds-staging.cck8zbm50hdd.us-east-1.rds.amazonaws.com
  username: tapjoy
  password: andoverbusiness1
  reconnect: true

production:
  adapter: mysql
  database: tapjoy_db
  host: tapjoy-db-rds.cck8zbm50hdd.us-east-1.rds.amazonaws.com
  username: tapjoy
  password: andoverbusiness1
  reconnect: true

job_runner:
  adapter: mysql2
  database: tapjoy_db
  host: tapjoy-db-rds.cck8zbm50hdd.us-east-1.rds.amazonaws.com
  username: tapjoy
  password: andoverbusiness1
  reconnect: true

production_slave_for_tapjoy_db:
  adapter: mysql
  database: tapjoy_db
  host: tapjoy-db-rds-replica2.cck8zbm50hdd.us-east-1.rds.amazonaws.com
  username: tapjoy
  password: xatrugAxu6
  reconnect: true

production_slave:
  adapter: mysql
  database: tapjoy_db
  host: replica.tapjoy.com
  username: tapjoy
  password: xatrugAxu6
  reconnect: true

sqlite:
  adapter: sqlite3
  database: db/webserver.sqlite

development_sqlite:
  adapter: sqlite3
  database: db/webserver-dev.sqlite
