api_url: https://staging.tapjoy.com
dashboard_url: https://staging.tapjoy.com
website_url: https://staging.tapjoy.com
masterjobs_url: https://staging.tapjoy.com
asset_host: https://d10hyk8bs4mjhv.cloudfront.net
