development:
  hosts:
    - ec2-50-17-5-126.compute-1.amazonaws.com
  port: 5433
  database: tapjoy
  user: prod
  password: taptaptap1234!

test:
  hosts:
    - ec2-50-17-5-126.compute-1.amazonaws.com
  port: 5433
  database: tapjoy
  user: prod
  password: taptaptap1234!

staging:
  hosts:
    - ec2-50-17-5-126.compute-1.amazonaws.com
  port: 5433
  database: tapjoy
  user: prod
  password: taptaptap1234!

production:
  hosts:
    - ec2-107-22-99-222.compute-1.amazonaws.com
    - ec2-107-22-27-186.compute-1.amazonaws.com
    - ec2-23-20-246-84.compute-1.amazonaws.com
    - ec2-174-129-136-184.compute-1.amazonaws.com
  port: 5433
  database: tapjoy
  user: prod
  password: taptaptap1234!
