#!/usr/bin/env ruby

if `uname` =~ /Darwin/
  command = "open"
elsif `uname` =~ /Linux/
  command = "xdg-open"
else
  puts "Unsupported operating system!"
  exit 1
end
system("#{command} https://github.com/Tapjoy/connect/compare/deploy...master")
