source :gemcutter

gem 'rcov', '0.9.11'
gem 'rdoc', '3.12'
gem 'rails', '3.0.6'
gem 'daemons', '1.0.10'
gem 'hpricot', '0.8.1'
gem 'httparty', '0.7.8'
gem 'json', '1.5.3'
gem 'libxml-ruby', '1.1.3', :require => 'xml'
gem 'memcached', '1.3.2'
gem 'mysql', '2.8.1'
gem 'nokogiri', '1.5.0'
gem 'patron', '0.4.4'
gem 'right_aws'
gem 'rmagick', '2.12.2', :require => 'RMagick'
gem 'sqlite3', '1.3.3'
gem 'typhoeus', '0.2.4'
gem 'therubyracer', '0.9.10', :require => 'v8'
gem 'SystemTimer', '1.2.3', :require => 'system_timer'
gem 'redis', '2.2.2'

gem 'acts-as-approvable', '0.6.9'
gem 'aws-sdk', '1.1.4'
gem 'airbrake', '3.0.5'
gem 'authlogic', :git => 'git://github.com/odorcicd/authlogic.git', :branch => 'rails3'
gem 'curbit', '0.2.0'
gem 'declarative_authorization'
gem 'differ', '0.1.2'
gem 'geoip', '1.1.1'
gem 'haml', '3.1.3'
gem 'hominid', '3.0.2'
gem 'htmlentities', '4.3.1'
gem 'mogli', '0.0.33'
gem 'newrelic_rpm', '3.3.0'
gem 'plist', '3.1.0'
gem 'read_from_slave', '0.4.0'
gem 'ruby-hmac', '0.4.0', :require => 'ruby_hmac'
gem 'sass', '3.1.15'
gem 'sendgrid', '1.0.1'
gem 'syslog-logger', '1.6.4', :require => 'syslog_logger'
gem 'uuidtools', '2.1.2'
gem 'vertica', '0.8.1'
gem 'will_paginate', '2.3.16'
gem 'hashie', '1.1.0'
gem 'multi_json', '1.0.3'
gem 'multi_xml', '0.4.0'
gem 'addressable', '2.2.6', :require => 'addressable/uri'
gem 'multipart-post', '1.1.0', :require => 'net/http/post/multipart'
gem 'faraday', '0.7.4'
gem 'faraday_middleware', '0.7.0'
gem 'simple_oauth', '0.1.5'
gem 'twitter', '1.7.2'
gem 'oauth', '0.4.5'
gem 'acts-as-approvable', '0.6.9'

gem 'hike', '1.2.1'
gem 'sprockets', '2.3.1'
gem 'execjs', '1.3.0'
gem 'uglifier', '1.2.3'
gem 'tilt', '1.3.3'
gem 'distribution', '0.7.0', :git => 'git://github.com/freefrancisco/distribution.git'

group :development, :staging do
  gem 'mail_safe', '0.3.1'
end

group :development do
  gem 'mongrel', '1.1.5'
end

group :test do
  gem 'factory_girl_rails', '~>1'
  gem 'shoulda', '2.11.1'
  gem 'shoulda-addons', '0.2.2', :require => 'shoulda_addons'
  gem 'mocha', '0.9.12'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'spork'
end

group :ops do
  gem 'unicorn', '4.2.0'
end
