source :rubygems
source 'https://gems.gemfury.com/NpbzcqYHo5hzMWudyHNj/'

gem 'activemerchant'
gem 'acts_as_approvable', '0.7.0'
gem 'activerecord-mysql2-adapter'
gem 'adapter-redis', '0.5'
gem 'addressable', '2.2.6', :require => 'addressable/uri'
gem 'analytics_logger', '0.8.11', :git => 'git@github.com:Tapjoy/analytics_logger.git', :tag => 'v0.8.11'
gem 'airbrake', '~> 3.0.0'
gem 'archive-tar-minitar'
gem 'asset_sync'
gem 'authlogic', :github => 'odorcicd/authlogic', :branch => 'rails3'
gem 'aws-sdk', '1.3.9'
gem 'bunny', '0.8.0.1', :git => 'git@github.com:Tapjoy/bunny.git', :tag => 'v0.8.0.1'
gem 'bzip2-ruby'
gem 'cancan', :github => 'Tapjoy/cancan', :tag => 'v2.0.0.0b'
gem 'chef', '0.10.8'
gem 'country-select'
gem 'curbit', '0.2.0'
gem 'daemons', '1.0.10'
gem 'declarative_authorization'
gem 'differ'
gem 'dynamic_form'
gem 'em-http-request', :require => 'em-http'
gem 'em-synchrony', :require => ['em-synchrony',
                                 'em-synchrony/em-http']
gem 'escape_utils', '0.2.4'
gem 'eventmachine', '~>1.0.0'
gem 'faraday', '0.7.4'
gem 'faraday_middleware', '0.7.0'
gem 'foreman', '0.36.1'
gem 'geoip', '1.1.1'
gem 'haml', '3.1.3'
gem 'hashie', '~>1.2'
gem 'hike', '1.2.1'
gem 'hominid', '3.0.2'
gem 'hpricot', '0.8.6'
gem 'htmlentities', '4.3.1'
gem 'httparty', '0.7.8'
gem 'jquery-rails'
gem 'json', '1.5.3'
gem 'kgio', '2.7.2'
gem 'lazy_high_charts', '1.2.2'
gem 'localeapp', :github => 'dickeyxxx/localeapp'
gem 'libxml-ruby', '2.3.3', :require => 'xml'
gem 'locales'
gem 'memcached', '1.3.2'
gem 'mogli', '0.0.38'
gem 'msgpack'
gem 'multi_json', '1.0.3'
gem 'multi_xml', '0.4.0'
gem 'multipart-post', '1.1.0', :require => 'net/http/post/multipart'
gem 'mysql', '2.8.1'
gem 'mysql2'
gem 'nokogiri', '1.5.5'
gem 'oauth', '0.4.5'
gem 'omniauth-tapjoy'
gem 'patron', '0.4.4'
gem 'plist', '3.1.0'
gem 'progress_bar'
gem 'rack-cors', '0.2.7'
gem 'rack-fiber_pool',  :require => 'rack/fiber_pool'
gem 'rails', '~>3.0.19'
gem 'rake'
gem 'rabl', '0.7.6'
gem 'rdoc', '3.12'
gem 'read_from_slave', '0.4.0'
gem 'redis', '2.2.2'
gem 'riak-client', '1.0.5'
gem 'right_aws', :git => 'git@github.com:Tapjoy/right_aws.git', :ref => 'em'
gem 'rmagick', '2.12.2', :require => 'RMagick'
gem 'rollout', '~> 2.0.0c'
gem 'ruby-hmac', '0.4.0', :require => 'ruby_hmac'
gem 'sass', '3.1.15'
gem 'savon', '1.1.0'
gem 'sendgrid', '1.0.1'
gem 'signage', :git => 'git@github.com:Tapjoy/signage.git'
gem 'simple_oauth', '0.1.5'
gem 'sprockets_rails3_backport', :github => 'dickeyxxx/sprockets_rails3_backport'
gem 'sqlite3', '1.3.3'
gem 'tilt', '1.3.3'
gem 'toystore', '0.10.2'
gem 'twitter', '~> 2.0.0'
gem 'typhoeus', '0.2.4'
gem 'uuidtools', '2.1.2'
gem 'vertica', '0.9.1'
gem 'will_paginate', '~> 3.0'
gem 'xml-simple', :require => 'xmlsimple'

gem 'notifications_client', :git => 'git@github.com:Tapjoy/notifications_client.git', :ref => '6594294b8570b63e318a9326f43dd7e427224d1d'

# This needs to be down here to get sdb stuff
#gem 'newrelic_rpm', '3.5.3.25'
gem 'newrelic_rpm', '3.5.3.rainbows', :git => 'git@github.com:joe1chen/rpm.git'
gem 'newrelic_riak', '0.1.1', :github => 'Tapjoy/newrelic-riak', :tag => 'v0.1.2'

group :development, :staging do
  gem 'mail_safe', '0.3.1'
end

group :development do
  gem 'annotate'
  gem 'thin'
  gem 'guard-spork'
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'rspec-instafail'
  gem 'growl'
  gem 'pry'
  gem 'pry-rails'
  gem 'awesome_print'
  gem 'pry-remote'
  gem 'pry-nav'
  gem 'ruby_parser'
  gem 'ruby18_source_location', :platforms => :ruby_18
  gem 'parallel_tests'
  gem 'rack-bug', :github => 'brynary/rack-bug', :branch => :rails3
end

group :test do
  gem 'capybara'
  gem 'cucumber'
  gem 'database_cleaner'
  gem 'factory_girl', '~>2.6'
  gem 'factory_girl_rails'
  gem 'launchy'
  gem 'spork'
  gem 'test_after_commit'
  gem 'timecop'
  gem 'vcr'
  gem 'fakeweb'
  gem "fakeredis", :require => "fakeredis/rspec"
  gem 'fakememcached', :git => 'git://github.com/Tapjoy/fakememcached.git', :ref => 'b722d'
end

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'cucumber-rails', :require => false
  gem 'shoulda-matchers', '1.2.0'
  gem 'dotenv'
end

group :ops do
  gem 'pry'
  #gem 'unicorn', '4.2.0'
  gem 'rainbows', '4.3.1'
end

platforms :ruby_18 do
  gem 'SystemTimer', '1.2.3', :require => 'system_timer'
  gem 'rcov'
end

platforms :ruby_19 do
  gem 'simplecov', :require => false
end
