source :rubygems

gem 'activemerchant'
gem 'acts-as-approvable', '0.6.9'
gem 'adapter-redis', '0.5'
gem 'addressable', '2.2.6', :require => 'addressable/uri'
gem 'airbrake', '3.0.5'
gem 'authlogic', :github => 'odorcicd/authlogic', :branch => 'rails3'
gem 'aws-sdk', '1.3.9'
gem 'country-select'
gem 'curbit', '0.2.0'
gem 'daemons', '1.0.10'
gem 'declarative_authorization'
gem 'differ'
gem 'distribution', '0.7.0', :github => 'Tapjoy/distribution'
gem 'dynamic_form'
gem 'faraday', '0.7.4'
gem 'faraday_middleware', '0.7.0'
gem 'foreman', '0.36.1'
gem 'geoip', '1.1.1'
gem 'haml', '3.1.3'
gem 'hashie', '1.1.0'
gem 'hike', '1.2.1'
gem 'hominid', '3.0.2'
gem 'hpricot', '0.8.1'
gem 'htmlentities', '4.3.1'
gem 'httparty', '0.7.8'
gem 'jquery-rails'
gem 'json', '1.5.3'
gem 'kgio', '2.7.2'
gem 'libxml-ruby', '1.1.3', :require => 'xml'
gem 'memcached', '1.3.2'
gem 'mogli', '0.0.33'
gem 'multi_json', '1.0.3'
gem 'multi_xml', '0.4.0'
gem 'multipart-post', '1.1.0', :require => 'net/http/post/multipart'
gem 'mysql', '2.8.1'
gem 'nokogiri', '1.5.5'
gem 'oauth', '0.4.5'
gem 'patron', '0.4.4'
gem 'plist', '3.1.0'
gem 'rails', '~>3.0.12'
gem 'rake'
gem 'rdoc', '3.12'
gem 'read_from_slave', '0.4.0'
gem 'redis', '2.2.2'
gem 'right_aws', :github => 'Tapjoy/right_aws'
gem 'rmagick', '2.12.2', :require => 'RMagick'
gem 'rollout', :github => 'Tapjoy/rollout'
gem 'ruby-hmac', '0.4.0', :require => 'ruby_hmac'
gem 'sass', '3.1.15'
gem 'sendgrid', '1.0.1'
gem 'simple_oauth', '0.1.5'
gem 'sprockets', '2.3.1'
gem 'sqlite3', '1.3.3'
gem 'syslog-logger', '1.6.4', :require => 'syslog_logger'
gem 'tilt', '1.3.3'
gem 'toystore', '0.10.2'
gem 'twitter', '1.7.2'
gem 'typhoeus', '0.2.4'
gem 'uglifier', '1.2.3'
gem 'uuidtools', '2.1.2'
gem 'vertica', '0.9.1'
gem 'will_paginate', '~> 3.0'
gem 'xml-simple', :require => 'xmlsimple'

# This needs to be down here to get sdb stuff
gem 'newrelic_rpm', '3.3.0'

group :development, :staging do
  gem 'mail_safe', '0.3.1'
end

group :development do
  gem 'annotate'
  gem 'thin'
  gem 'guard-spork'
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'rspec-instafail'
  gem 'ruby_gntp'
  gem 'pry'
  gem 'pry-rails'
  gem 'awesome_print'
  gem 'pry-remote'
  gem 'pry-nav'
  gem 'ruby18_source_location', :platforms => :ruby_18
  gem 'parallel_tests'
end

group :test do
  gem 'capybara'
  gem 'cucumber'
  gem 'database_cleaner'
  gem 'factory_girl_rails', '1.2.0'
  gem 'launchy'
  gem 'spork'
  gem 'timecop'
  gem "fakeredis", :require => "fakeredis/rspec"
end

group :development, :test do
  gem 'rspec', '~> 2.10.0'
  gem 'rspec-rails', '~> 2.10.0'
  gem 'cucumber-rails', :require => false
  gem 'shoulda-matchers'
end

group :ops do
  gem 'pry'
  gem 'unicorn', '4.2.0'
end

platforms :ruby_18 do
  gem 'SystemTimer', '1.2.3', :require => 'system_timer'
  gem 'rcov'
end

platforms :ruby_19 do
  gem 'simplecov', :require => false
end
