# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'rake'

Tapjoyad::Application.load_tasks

# Load the annotate gem's rake tasks
Dir["#{Gem.searcher.find('annotate').full_gem_path}/**/tasks/**/*.rake"].each {|ext| load ext}
# TODO: For newer rubygems
# Dir["#{Gem::Specification.find_by_name("annotate").full_gem_path}/**/tasks/**/*.rake"].each {|ext| load ext}

ENV['position_in_class']   = "before"
ENV['exclude_tests']       = "true"
ENV['exclude_fixtures']    = "true"
