---
de:
  activerecord:
    errors:
      full_messages:
        format: ~
      messages:
        accepted: ~
        blank: ~
        confirmation: ~
        empty: ~
        equal_to: ~
        even: ~
        exclusion: ~
        greater_than: ~
        greater_than_or_equal_to: ~
        inclusion: ~
        invalid: ~
        less_than: ~
        less_than_or_equal_to: ~
        not_a_number: ~
        not_an_integer: ~
        odd: ~
        record_invalid: ~
        taken: ~
        too_long: ~
        too_short: ~
        wrong_length: ~
      template:
        body: ~
        header:
          one: ~
          other: ~
  date:
    abbr_day_names: ~
    abbr_month_names: ~
    day_names: ~
    formats:
      default: ~
      long: ~
      short: ~
    month_names: ~
    order: ~
  datetime:
    distance_in_words:
      about_x_hours:
        one: ~
        other: ~
      about_x_months:
        one: ~
        other: ~
      about_x_years:
        one: ~
        other: ~
      almost_x_years:
        one: ~
        other: ~
      half_a_minute: ~
      less_than_x_minutes:
        one: ~
        other: ~
      less_than_x_seconds:
        one: ~
        other: ~
      over_x_years:
        one: ~
        other: ~
      x_days:
        one: ~
        other: ~
      x_minutes:
        one: ~
        other: ~
      x_months:
        one: ~
        other: ~
      x_seconds:
        one: ~
        other: ~
    prompts:
      day: ~
      hour: ~
      minute: ~
      month: ~
      second: ~
      year: ~
  errors:
    format: ~
    messages:
      accepted: ~
      blank: ~
      confirmation: ~
      empty: ~
      equal_to: ~
      even: ~
      exclusion: ~
      greater_than: ~
      greater_than_or_equal_to: ~
      inclusion: ~
      invalid: ~
      less_than: ~
      less_than_or_equal_to: ~
      not_a_number: ~
      not_an_integer: ~
      odd: ~
      too_long: ~
      too_short: ~
      wrong_length: ~
  helpers:
    select:
      prompt: ~
    submit:
      create: ~
      submit: ~
      update: ~
  number:
    currency:
      format:
        delimiter: ~
        format: ~
        precision: ~
        separator: ~
        significant: ~
        strip_insignificant_zeros: ~
        unit: ~
    format:
      delimiter: ~
      precision: ~
      separator: ~
      significant: ~
      strip_insignificant_zeros: ~
    human:
      decimal_units:
        format: ~
        units:
          billion: ~
          million: ~
          quadrillion: ~
          thousand: ~
          trillion: ~
          unit: ~
      format:
        delimiter: ~
        precision: ~
        significant: ~
        strip_insignificant_zeros: ~
      storage_units:
        format: ~
        units:
          byte:
            one: ~
            other: ~
          gb: ~
          kb: ~
          mb: ~
          tb: ~
    percentage:
      format:
        delimiter: ~
    precision:
      format:
        delimiter: ~
  support:
    array:
      last_word_connector: ~
      two_words_connector: ~
      words_connector: ~
    select:
      prompt: ~
  text:
    featured:
      download: Download
      download_and_run: "Einfach downloaden und los"
      earn_currency: "Erhalte %{amount_and_currency}"
      earn_now: "Jetzt erhalten"
      show_more_apps: "Mehr Apps anzeigen"
      skip: Weiter
      title: "Erhalte %{currency}"
      try_out: "Jetzt ausprobieren"
    footer:
      about: ~
      advertisers: ~
      blog: ~
      copyright: ~
      developers: ~
      privacy: ~
    games:
      about_body: "Liebe die Apps die Sie haben, finde die Apps die Sie lieben"
      about_title: "Irgendwie weiß es genau was für Apps Ich mag."
      account_created_body: "Ihre Tapjoy Konto wurde erfolgreich erstellt!"
      account_created_title: Erfolg!
      action_required: "Aktion erforderlich!"
      active_gamers_text: "%{count} benutzen"
      add: hinzufügen
      add_to_homescreen: "Füge %{tapjoy} in Ihren Home-Bildschirm ein."
      advertisers_body: "Erreiche Millionen von User und bekomme Engagement für Ihre Produkte"
      advertisers_title: Werbetreibende
      allow_marketing_emails: "Erlauben Sie Tapjoy Marketing E-mails durch zusenden"
      almost_done: ~
      already_registered:
        one: "%{name} hat bereits registriert, ab sofort folgen Sie ihm / ihr"
        other: "%{name} hat bereits registriert, ab sofort folgen Sie ihnen"
      amount_and_currency: "%{amount} %{currency}"
      back_to_top: "Nach Oben Gehen"
      birthdate: Geburtsdatum
      browse_offers: "Angebote durchsuchen"
      call_to_action_body: "Liebe die Apps die Sie haben, finde die Apps die Sie lieben"
      call_to_action_title: "Entsperren Sie Ihre Handy Freude!"
      cant_fetch_offers: "Es gab ein Problem weitere Angebote zu holen. Bitte versuchen Sie es erneut."
      change: ändern
      change_linked_account: "Verlinkte Konto ändern"
      choose_section: "Wählen Sie eine Seite"
      close: ~
      collect: Sammele
      collect_rewards: "Belohnungen sammeln"
      connect_my_device: "Mein Gerät verbinden"
      connect_to_facebook: "Klicken Sie hier um mit Facebook zu verbinden"
      connect_your_android: "Bitte verbinden Sie Ihren Android Gerät"
      connect_your_device: "Bitte verbinden Sie Ihr Gerät"
      connected_to_facebook: ~
      connected_to_twitter: ~
      contact_support: "Kundendienst Kontaktieren"
      contact_us: "Tapjoy Kontaktieren"
      cookies_required: "Aktivieren Sie bitte Ihrem Browser-Cookies"
      deactivate: Deaktivieren
      del_acct_confirm: "Klicken Sie auf der untere Taste, um Ihrem Konto zu deaktivieren. Sobald ein Konto für %{days_before_deletion} Tagen deaktiviert ist, wird es komplett gelöscht werden. Wir können Ihrem Konto nicht wiederherstellen, wenn es gelöscht worden ist."
      delete_my_account: "Mein Konto löschen"
      developers_body: "Treiben Sie bedeutsames Umsatz Zu Ihren Apps mit unseren Monetarisierungs-Dienste"
      developers_title: Entwickler
      discover_apps: ~
      download_now: ~
      earn: "%{currency} Verdienen"
      earn_rewards: ~
      earn_title: "Führen Sie eine der folgenden Angebote um %{currency} für %{app_name} zu verdienen"
      earning_rewards: ~
      edit: bearbeiten
      email_device_link: ~
      email_notification: "E-Mail Benachrichtigungen"
      enable_javascript: "Bitte gehen Sie in Ihren Browser-Einstellungen und aktivieren Sie JavaScript, um weiter mit Tapjoy zu verwenden."
      enter_birthdate: "Bitte geben Sie Ihrem Geburtsdatum"
      enter_email: "Bitte geben Sie Ihre E-address ein"
      enter_message: "Bitte geben Sie eine Nachricht"
      enter_name: ~
      enter_password: "Bitte geben Sie ein Passwort"
      enter_platform: "Bitte wählen Sie iOS oder Android"
      enter_tos: "Bitte stimmen Sie zu den genannten Bedingungen"
      enter_valid_email: "Geben Sie eine gültige E-Mail-Adresse"
      error_mark_as_favorite: ~
      error_unmark_as_favorite: ~
      failed_to_change_linked: ~
      favorite_app: Lieblingsapp
      favorite_apps: Lieblingsapps
      favorite_category: Lieblingskategorie
      favorites: ~
      feedback: Feedback
      find_and_invite_friends: "Finde und Lade Freunde Ein"
      find_friends_from_facebook: ~
      find_friends_from_twitter: ~
      find_friends_on_tapjoy: "Finde Freunde über andere Netze die bereits Tapjoy schon nutzen"
      find_more_friends: "Finde mehr Freunde"
      find_new_apps: "Finden Sie Neue Apps"
      follow_us: "Folge uns"
      forgot_pass: "Passwort vergessen?"
      free: ~
      generic_issue: "Es gab ein Problem. Bitte versuchen Sie es erneut."
      get_app: "App holen"
      get_it: "Jetzt bekommen!"
      grant_us_access: "Bitte gestatten Sie uns / gib uns beide Berechtigungen vor Zusendung einer Einladung"
      how_it_works_body: "Alle Ihre Spiele sind unten gelistet. Klicken Sie auf die Tasten neben den Apps um Währung zu verdienen ."
      how_it_works_title: "Wie funktioniert es?"
      install_and_run: "Installieren und starten Sie %{name}"
      install_android_app: ~
      install_profile: ~
      invalid_fields: ~
      invite: "Meine Freunde einladen!"
      invite_by_email: "Einladung per E-mail"
      invite_email_body: |-
          %{name} hat Sie bei Tapjoy eingeladen, der beste Ort um die heißesten neuen apps zu finden. Die Anmeldung ist kostenlos und Sie haben die Möglichkeit die besten Apps auf iOS und Android zu entdecken, während Sie auch Währung in Ihrem Lieblings-Apps verdienen können. Keine

          Notwendigkeit, durch Tausende von Apps im App Store oder dem Android Marktplatz zu waten, um Ihren nächsten Download zu finden. Tapjoy wird Ihnen helfen und empfiehlt apps die wir wissen, Sie mögen werden.

          Zu Starten, erstellen Sie Ihr Konto hier:
      invite_email_greet: Hallo
      invite_email_signature: "Team Tapjoy"
      invite_friends: ~
      invite_title: "Sende eine E-mail einladung"
      invites_sent_to: ~
      issue_registering: "Es gab ein Problem bei der Registrierung von Ihren Konto"
      join_the_community: ~
      join_the_community_blurb: ~
      last_played: "Letztens Gespielt"
      link_account_header: ~
      link_account_messaging: ~
      link_account_messaging_android_href: ~
      link_account_messaging_tjm_href: ~
      link_my_facebook: "Mein Facebook Verlinken"
      load_more: "Mehr Laden"
      loading: Lädt..
      log_in_tapjoy: "Bei Tapjoy Einloggen"
      mark_as_favorite: "Zu Favoriten hinzufügen"
      member_since: "Mitglied Seid %{date}"
      meta_description: "Tapjoy: Das Ziel für Handy Apps und Spiele auf Android, iPhone und iPad."
      meta_keywords: "Spiele, Handy Spiele, Handy Apps, iOS, Android, iPhone, iTouch"
      more_apps: "Weitere Apps"
      more_the_merrier: "Es macht Spass mit mehr!"
      my_apps: "Meine Apps"
      next: Nächste
      no_device: "Kein Gerät Gefunden"
      no_javascript: "Bitte gehen Sie in Ihren Browser-Einstellungen und aktivieren Sie JavaScript, um weiter mit Tapjoy zu verwenden."
      none_selected: "Keine Auswahl"
      on_my: "Auf mein %{device}"
      oops: Oops!
      or_learn_more: ~
      other_options: "Weiter Optionen"
      our_tos_changed: "Unsere %{terms_of_use} haben sich geändert. Bitte lesen Sie und geben Sie Ihre Zustimmung unten."
      password_changed: ~
      password_non_match: ~
      post_to_facebook: ~
      post_to_facebook_content: "Checken Sie Tapjoy, wo Sie die besten neuen Apps und Spiele entdecken kann, während Sie auch Währung für die Apps die Sie Lieben verdienen können. Melden Sie sich Gratis bei tapjoy.com um die richtige App Empfehlungen jetzt zu bekommen!"
      privacy_policy_href: Datenschutzrichtlinie
      profile: Ich
      profile_error: ~
      profile_update: ~
      provide_other_email: "Bitte geben Sie eine andere E-Mail Adresse"
      recipients_label: "Mit Kommas, mehrere E-mail adressen trennen"
      recommend_apps: ~
      recommendations: "Heiße Empfehlungen"
      recommendations_smart: "Heiße Empfehlungen"
      registering: "Registrierung folgt.."
      report_bug: "Fehler melden"
      reset_password_message: "Geben Sie die E-Mail-Adresse die mit Ihrem Konto verbunden ist und wir schicken Ihnen einen Link zum Zurücksetzen Ihres Passworts."
      reset_password_message_submit: "Sie werden in den nächsten Minuten eine E-Mail mit Anweisungen erhalten, um Ihren Passwort  zurückzusetzen."
      reset_password_retry: "Wenn Sie immer noch Probleme bei der Anmeldung haben, Sie können %{reset_password_url} oder E-Mail"
      reset_password_retry_url_text: "Fordern Sie eine neue E-Mail-Passwort-Zurücksetzung"
      review_app_name: "Bewerte %{app_name}"
      review_created: "Bewertung dieses App ist Erfolgreiche"
      review_issue: "Es gab ein Problem. Bitte versuchen Sie es später erneut."
      review_updated: "App Bewertung wurde erfolgreich aktualisiert"
      reviewed_already: "Sie haben bereits diese App bewertet."
      select_current_device: "Bitte wählen Sie Ihr aktuelles Gerät"
      select_device: "Bitte wählen Sie Ihr Gerät"
      select_friend: "Bitte wählen Sie mindestens einen Freund vor dem Versenden eine Einladung"
      share_on_facebook: "Auf Facebook Teilen"
      share_on_twitter: Twittern
      share_with_everyone: "Mit allen Teilen"
      share_with_your_friends: "Mit Ihre Freunde Teilen"
      social_networks: "Soziale Netzwerk"
      social_settings: "Sozialen Einstellungen"
      spread_mobile_joy: ~
      start_discovering: ~
      tap_that: "Einfach Tippen %{icon} und %{button} Auswählen"
      tapjoy_picks: "Tapjoy Empfehlt"
      terms_of_use_href: Nutzungsbedingungen
      thanks_contact_support: "Wir danken Ihnen dass Sie bei unseren Support gemeldet haben. Einer unserer Mitarbeiter wird so bald wie möglich mit ihnen kontakt herstellen."
      thanks_contact_us: "Vielen Dank für Ihre Kontaktaufnahme. Wir werden uns an Ihnen so bald wie möglich Zurückmelden."
      thanks_feedback: "Vielen Dank für Ihren Feedback!"
      thanks_report_bug: "Vielen Dank für den Hinweis auf Fehler. Wir werden dass so bald wie möglich überprüfen."
      thats_you: "das sind Sie"
      tos_acknowledge_html: "Wenn dieses Feld markiert ist, behaupte ich dass ich zu dem %{terms_of_use} & %{privacy_policy} zu stimme"
      tos_change_acknowledge: "Wenn dieses Feld markiert ist, behaupte ich dass ich zu dem Nutzungsbedingungen zu stimme"
      unable_to_process: "Leider könnten wir Ihre Anfrage nicht verarbeiten"
      unlock_mobile_joy: "Handy Freude Entsperren!"
      unmark_as_favorite: ~
      welcome_tapjoy: ~
      wifi_required: "Wifi nötig"
      wrong_device: "Falsches Gerät?"
      you_are_following: ~
      your_followers:
        one: ~
        other: ~
    instructions:
      amount_and_currency: "%{amount} %{currency}"
      continue_link: "Klicke hier um fortzufahren."
      download_action: hier
      download_link: "Wenn Du diese App nicht besitzt, klicke %{download_action} um sie downzuloaden."
      earn_currency: "Erhalte %{amount_and_currency}"
      footer: "Nachdem Du diese Schritte abgeschlossen hast, erhältst Du %{amount_and_currency}."
      header: "Folge diesen Schritten um %{currency} zu erhalten:"
      title: Anleitung
    offerwall:
      buy_currency: "Kaufe %{amount} %{currency}"
      earn_currency: "Erhalte %{amount} %{currency}"
      free: ~
      instructions: "Nimm an einer der folgenden Aktionen teil um %{currency} zu erhalten"
      instructions_non_rewarded: "Discover what's hot on Tapjoy!"
      load_error: "Bitte versuche es nochmal!"
      load_more: "Lade noch mehr!"
      loading: Lade...
      missing_currency: "Fehlende %{currency}?"
      more_offers: "Möchten Sie mehr Angebote sehen? Besuchen Sie Tapjoy um Belohnungen zu verdienen und persönliche Apps Empfehlungen zu bekommen!"
      next: "Nächste %{items} "
      popular_apps: "Popular Apps"
      previous: "Vorherige %{items}"
      title: "Erhalte %{currency}"
      wifi_required: "Wifi nötig"
      wifi_warning: "This app requires a wifi connection to download."
    shared:
      about_link: "Über Tapjoy"
      ads_by: "Werbung von"
      android: Android
      back: Zurück
      blog: Blog
      cancel: Absagen
      change_password: "Passwort ändern"
      city: Stadt
      collect: Sammele
      comment: Kommentar
      confirm_password: "Passwort bestätigen"
      continue: Weiter
      copyright: "Urheberrecht %{year} Tapjoy, Inc. Alle Rechte vorbehalten. Tapjoy und dass Tapjoy logo sind Warenzeichen oder eingetragenen Warenzeichen von Tapjoy, Inc.  Alle Drittwerbenden Logos und Warenzeichen erwähnt sind das Eigentum ihrer jeweiligen Besitzer."
      country: Land
      day: Tag
      earn_verb: Verdienen
      email: E-mail
      facebook_profile: "Facebook Profil"
      favorites: Favoriten
      female: Weiblich
      followers: Folger
      following: Folgen
      friends: Freunde
      gender: Geschlecht
      help: Hilfe
      invite: Einladung
      ios: iOS
      join: Teilnehmen
      location: Standort
      login_noun: Einloggen
      login_verb: Einloggen
      logout: Ausloggen
      male: Männlich
      month: Monat
      my_account: "Mein Konto"
      my_profile: "Mein Profil"
      my_reviews: "Meine Bewertungen"
      name: Name
      new_password: "Neue Passwort"
      nickname: Spitzname
      none: ~
      ok: Ok
      options: Optionen
      other: Sonstiges
      password: Passwort
      please_try_again: ~
      preferences: Einstellungen
      privacy: Privat
      privacy_policy: Datenschutzrichtlinie
      profile: Profil
      rate_and_review: Bewertung
      recipients: Empfänger
      reset_password: "Passwort Zurückstellen"
      reviews: Bewertungen
      save: Speichern
      send: Schicken
      sending: ~
      sent: ~
      share: Mitteilen
      sign_in: Einloggen
      sign_up: Anmelden
      submit: Abgeben
      submit_review: "Bewertung Abgeben"
      success: Erfolg!
      title_noun: Titel
      try_again: "Neu versuchen"
      unknown: Unbekannt
      update_review: "Bewertung Aktualisieren"
      updating: Aktualisierung
      view_all: ~
      write_review: "Bewertung Schreiben"
      year: Jahr
      zip_postal: Postleitzahl
    support:
      abuse_warning: "Dieses Formular ist nur für Benutzer, die nicht für eine abgeschlossene Angebot belohnt wurden sind. Missbrauch dieser Seite können Zu den Schließung Ihres Kontos führen und dass verboten bei weiteren Angeboten in der Zukunft zu Beteilen."
      description_label: "Beschreibung:"
      email_address_label: "E-Mail-Adresse:"
      instructions_1: "Bitte wählen Sie das Angebot wo Sie keine %{currency} Erhalten haben und geben Sie Ihre E-Mail-Adresse."
      instructions_2: "Wenn Sie ein Ticket mit unvollständigen Angaben schicken, kann es zu einer Verzögerung bei der Problem führen. Priorität werden für alle vollständige Angaben gegeben."
      invalid_email: "Bitte geben Sie eine gültige E-Mail-Adresse."
      message: "Leider ist %{offer} nicht mehr verfügbar. Sie können auf die vorherige Seite zurückkehren und aktualisieren um das neueste Angebot anzuzeigen."
      missing_description: "Bitte beschreiben Sie das Angebot dass Sie fertig gestellt haben."
      missing_offer: "Sie müssen das abgeschlossen Angebot angeben"
      no_incomplete_offers_label: "Es wurden keine passenden Angebote gefunden."
      optional_message: "Oder, hier klicken um %{offer} sowieso herunter zu laden."
      select_offer: "Angebot Auswählen"
      specify_offer_label: "Angebot angeben"
      submit_support_request: "Kundenservice Anfrage angeben"
      support_request_submitted: "Kundenservice Anfrage eingereicht"
      thanks: "Vielen Dank für Ihre Kundenservice Anfrage . Sie erhalten Ihre %{currency}, nachdem wir überprüft haben, dass Sie das Angebot fertig gestellt haben."
      title: "Verlorene %{currency}?"
      unavailable_offer: ~
    unavailable_offer:
      message: ~
      optional_message: ~
  time:
    am: ~
    formats:
      classic_short: ~
      day: ~
      day_long: ~
      day_short: ~
      default: ~
      long: ~
      short: ~
    pm: ~
