--- 
es: 
  activerecord: 
    errors: 
      full_messages: 
        format: "%{attribute} %{message}"
      messages: 
        accepted: "tienes que aceptar"
        blank: "no puede estar vacío"
        confirmation: "no es idéntico"
        empty: "can't be empty"
        equal_to: "tiene que ser igual a %{count}"
        even: "tiene que ser el mismo"
        exclusion: "está reservado"
        greater_than: "tiene sue ser superior a %{count}"
        greater_than_or_equal_to: "tiene que ser superior o igual a %{count}"
        inclusion: "no está incluido en la lista"
        less_than: "tiene que ser inferior a %{count}"
        less_than_or_equal_to: "tiene que ser inferior o igual a %{count}"
        not_a_number: "no es un número"
        not_an_integer: "no es un número entero"
        odd: "tiene que ser impar"
        record_invalid: "Inválido: %{errors}"
        taken: "ya está en uso"
        too_long: "es demasiado largo (el máximo es de %{count} carácteres)"
        too_short: "es demasiado corto (el mínimo es de %{count} carácteres)"
        wrong_length: "is the wrong length (should be %{count} characters)"
      models: 
        gamer_sessions: 
          attributes: 
            email: Email
            password: Password
      template: 
        body: "Hay problemas con los campos siguientes:"
        header: 
          one: "No se pudo guardar este %{model} por 1 problema"
          other: "%{count} errores han impedido guardar este %{model}"
  authlogic: 
    error_messages: 
      login_not_found: "Email incorrecto"
      password_invalid: "Contraseña incorrecta"
  errors: 
    format: "%{attribute} %{message}"
    messages: 
      accepted: "tiene que ser aceptado"
      blank: "no puede ser vacío"
      confirmation: "no es correcto"
      empty: "no puede ser vacío"
      equal_to: "tiene que ser igual a %{count}"
      even: "tiene que ser idéntico"
      exclusion: "está ya en uso"
      greater_than: "tiene que ser superior a %{count}"
      greater_than_or_equal_to: "tiene que ser superior o igual a %{count}"
      inclusion: "no está incluido en la lista"
      less_than: "tiene que ser inferior a %{count}"
      less_than_or_equal_to: "tiene que ser inferior o igual a %{count}"
      not_a_number: "no es un número"
      not_an_integer: "debe ser un número entero"
      odd: "tiene que ser impar"
      too_long: "es demasiado largo (el máximo es de %{count} carácteres)"
      too_short: "es demasiado corto (el mínimo es de %{count} carácteres)"
      wrong_length: "is the wrong length (should be %{count} characters)"
  helpers: 
    select: 
      prompt: "Por favor, selecciona"
    submit: 
      create: "Crea %{model}"
      submit: "Guarda %{model}"
      update: "Actualiza %{model}"
  support: 
    array: 
      last_word_connector: ", y "
      two_words_connector: " y "
      words_connector: ", "
    select: 
      prompt: "Por favor, selecciona"
  text: 
    footer: 
      about: "Acerca de Tapjoy"
      advertisers: Anunciantes
      blog: Blog
      developers: Desarrolladores
      privacy: "Privacidad"
    games: 
      app_review_concern_reported: "Reportar un problema"
      app_review_h_no: "No"
      app_review_h_yes: "Sí"
      app_review_more: más...
      app_review_report_concern: "Reportar un problema"
      app_review_thanks_for_feedback: "Gracias por tu mensaje"
      app_review_was_helpful: "¿Te ha sido útil esta reseña?"
      connected_to_facebook: "Conectado a Facebook"
      connected_to_twitter: "Conectado a Twitter"
      discover_apps: "Únete a los millones de aficionados a las aplicaciones en Tapjoy, y descubre las mejores apps. ¡Empieza ahora!"
      download_now: "Descarga ahora"
      email_device_link: "Email device link"
      enter_name: "Por favor, introduce un nombre"
      errno_error: "Problema de conectividad. Por favor, vuelve a intentar."
      error_mark_as_favorite: "Ha ocurrido un fallo cuando has intentado poner esta app entre tus favoritos"
      error_unmark_as_favorite: "Ha ocurrido un fallo cuando has intentado quitar esta app de tus favoritos"
      facebook_connect_failed: "El access a tu perfil de Facebook ha fallado"
      failed_to_change_linked: "No se ha podido cambiar la cuenta."
      favorites: Favorites
      find_friends_from_facebook: "Encontrar a tus amigos en Facebook"
      find_friends_from_twitter: "Encontrar a tus amigos en Twitter"
      friend_filter_label: "Introduce un nombre"
      grant_permissions_for_invite: "Por favor, danos tu permiso antes de mandar esta invitación."
      install_android_app: "Descarga la aplicación de Tapjoy en tu teléfono móvil."
      invalid_emails: "Una de las direcciones de correo electrónico no es correcta"
      invite_friends: 
        one: Invite
        other: "Invitar a %{count} amigos"
      invite_twitter_followers: "¡Invita a seguidores de Twitter!"
      invites_sent_to: 
        one: "Se ha mandado una invitación a %{name}"
        other: "Se han mandado invitaciones a %{name}"
      link_account_messaging_android_href: "Descargar la aplicación para Android"
      link_account_messaging_tjm_href: www.tapjoy.com
      mogli_reach_limit_error: "Haz alcanzado el límite. Por favor, vuelve a intentar."
      or_learn_more: "o aprende más"
      password_non_match: "La contraseña y su confirmación no son idénticas"
      please_connect_facebook: "Por favor, conecta tu cuenta de Facebook"
      post_to_facebook: "¡Publícalo en Facebook!"
      profile_error: "No se ha podido actualizar correctamente tu perfil."
      provide_single_email: "Por favor, indícanos una dirección de correo electrónico"
      reactivated_account: "Se ha reactivado tu cuenta con éxito"
      scheduled_for_deletion: "Has desactivado tu cuenta. Se borrará próximamente."
      social_invite_friend_error: "No se ha podido invitar a tu amigo, vuelve a intentar más tarde."
      social_need_authorize_error: "Por favor, confīrmanos que podemos mandar la invitación."
      social_to_next: "SIGUIENTE %{page_size}"
      social_to_prev: "ANTERIOR %{page_size}"
      social_to_top: "TOP &#8679;"
      spread_mobile_joy: "Invita a tus amigos a Tapjoy"
      start_discovering: "Descubre Tapjoy ahora, ¡es gratis!"
      twitter_at_least_one_friend_error: "Por favor, include por lo menos a un amigo en la invitación"
      twitter_authenticate_error: "Ha ocurrido un error durante la conexión a tu cuenta de TWITTER."
      twitter_forbidden_error: "Requests are being denied due to update limits."
      twitter_general_error: "Ha ocurrido un fallo en Twitter. Por favor, vuelve a intentar más tarde."
      twitter_internal_error: "Ha ocurrido un fallo en Twitter. Por favor, vuelve a intentar más tarde."
      twitter_invite_msg: "te ha invitado a Tapjoy, EL mejor sitio para encontrar las mejores aplicaciones. ¡Regístrate ahora, es gratis!"
      twitter_invite_title: "Por favor, invita a amigos para invitar en Twitter, via DM"
      unmark_as_favorite: "Quitar de tus Favoritos"
      welcome_tapjoy: "Bienvenido a Tapjoy!"
      you_are_following: "Estás siguiendo a (%{count})"
      your_followers: 
        one: "Tu seguidor"
        other: "Tus seguidores (%{count})"
    shared: 
      please_try_again: "Por favor, vuelve a intentar."
      sending: Sending
      sent: Sent
      view_all: "Ver todo"
    unavailable_offer: 
      message: "Sentimos las molestias, pero %{offer} ya no está disponible. Puedes volver a la página anterior y actualizarla para ver las ofertas más recientes." 
      optional_message: "O, haz click aquí para descargar %{offer} igual."
