--- 
ja: 
  activerecord: 
    errors: 
      full_messages: 
        format: "%{attribute} %{message}"
      messages: 
        accepted: "must be accepted"
        blank: "can't be blank"
        confirmation: "doesn't match confirmation"
        empty: "can't be empty"
        equal_to: "must be equal to %{count}"
        even: "must be even"
        exclusion: "is reserved"
        greater_than: "must be greater than %{count}"
        greater_than_or_equal_to: "must be greater than or equal to %{count}"
        inclusion: "is not included in the list"
        less_than: "must be less than %{count}"
        less_than_or_equal_to: "must be less than or equal to %{count}"
        not_a_number: "is not a number"
        not_an_integer: "must be an integer"
        odd: "must be odd"
        record_invalid: "Validation failed: %{errors}"
        taken: "has already been taken"
        too_long: "is too long (maximum is %{count} characters)"
        too_short: "is too short (minimum is %{count} characters)"
        wrong_length: "is the wrong length (should be %{count} characters)"
      models: 
        gamer_sessions: 
          attributes: 
            email: Email
            password: Password
      template: 
        body: "There were problems with the following fields:"
        header: 
          one: "1 error prohibited this %{model} from being saved"
          other: "%{count} errors prohibited this %{model} from being saved"
  authlogic: 
    error_messages: 
      login_not_found: "Email is invalid"
      password_invalid: "Password is invalid"
  errors: 
    format: "%{attribute} %{message}"
    messages: 
      accepted: "must be accepted"
      blank: "can't be blank"
      confirmation: "doesn't match confirmation"
      empty: "can't be empty"
      equal_to: "must be equal to %{count}"
      even: "must be even"
      exclusion: "is reserved"
      greater_than: "must be greater than %{count}"
      greater_than_or_equal_to: "must be greater than or equal to %{count}"
      inclusion: "is not included in the list"
      less_than: "must be less than %{count}"
      less_than_or_equal_to: "must be less than or equal to %{count}"
      not_a_number: "is not a number"
      not_an_integer: "must be an integer"
      odd: "must be odd"
      too_long: "is too long (maximum is %{count} characters)"
      too_short: "is too short (minimum is %{count} characters)"
      wrong_length: "is the wrong length (should be %{count} characters)"
  helpers: 
    select: 
      prompt: "Please select"
    submit: 
      create: "Create %{model}"
      submit: "Save %{model}"
      update: "Update %{model}"
  support: 
    array: 
      last_word_connector: ", and "
      two_words_connector: " and "
      words_connector: ", "
    select: 
      prompt: "Please select"
  text: 
    footer: 
      about: "About Tapjoy"
      advertisers: Advertisers
      blog: Blog
      developers: Developers
      privacy: "Privacy Policy"
    games: 
      app_review_concern_reported: "Concern Reported"
      app_review_h_no: "No"
      app_review_h_yes: "Yes"
      app_review_more: more...
      app_review_report_concern: "Report concern"
      app_review_thanks_for_feedback: "Thank you for your feedback"
      app_review_was_helpful: "Was this review helpful?"
      connected_to_facebook: "Connected to Facebook"
      connected_to_twitter: "Connected to Twitter"
      discover_apps: "Join the millions of mobile app lovers on Tapjoy and discover the best-rated apps. Get started today!"
      download_now: "Download now"
      email_device_link: "Email device link"
      enter_name: "Please enter your name"
      errno_error: "There was a connection issue. Please try again later."
      error_mark_as_favorite: "Error marking app as Favorite"
      error_unmark_as_favorite: "Error unmarking app as Favorite"
      facebook_connect_failed: "Failed to connect to your Facebook profile"
      failed_to_change_linked: "Failed to change linked account."
      favorites: Favorites
      find_friends_from_facebook: "Find friends from Facebook"
      find_friends_from_twitter: "Find friends from Twitter"
      friend_filter_label: "Start Typing a Name"
      grant_permissions_for_invite: "Please grant us both permissions before sending out an invite."
      install_android_app: "Download the Tapjoy app on your Android device to get started."
      invalid_emails: "The email(s) provided were invalid"
      invite_twitter_followers: "Invite Twitter Followers!"
      link_account_messaging_android_href: "download the Android app"
      link_account_messaging_tjm_href: www.tapjoy.com
      mogli_reach_limit_error: "You have reached the limit. Please try again later."
      or_learn_more: "or learn more"
      password_non_match: "Password and Confirmation do not match"
      please_connect_facebook: "Please connect your Facebook account"
      profile_error: "There was an error updating your profile."
      provide_single_email: "Please provide at least one email"
      reactivated_account: "Your account has been reactivated!"
      scheduled_for_deletion: "Your account has been deactivated and scheduled for deletion!"
      social_invite_friend_error: "There was an issue with inviting your friend, please try again later."
      social_need_authorize_error: "Please authorize us before sending out an invite."
      social_to_next: "NEXT %{page_size}"
      social_to_prev: "PREV %{page_size}"
      social_to_top: "TOP &#8679;"
      spread_mobile_joy: "Spread mobile joy"
      start_discovering: "Start discovering with Tapjoy for free"
      twitter_at_least_one_friend_error: "You must select at least one friend before sending out an invite"
      twitter_authenticate_error: "Error while authenticating via TWITTER. The service did not return valid data."
      twitter_forbidden_error: "Requests are being denied due to update limits."
      twitter_general_error: "Something happened to Twitter. Please try again later."
      twitter_internal_error: "Something happened to Twttier. Please try again later"
      twitter_invite_msg: "has invited you to join Tapjoy, the BEST place to find the hottest apps. Signing up is free!"
      twitter_invite_title: "Please Select Twitter Friends to Invite via DM"
      unmark_as_favorite: "Remove from Favorites"
      welcome_tapjoy: "Welcome to Tapjoy!"
      you_are_following: "You're following (%{count})"
      your_followers: 
        one: "Your follower"
        other: "Your followers (%{count})"
    shared: 
      please_try_again: "Please try again."
      sending: Sending
      sent: Sent
      view_all: "View All"
    unavailable_offer: 
      message: "We're sorry but %{offer} is no longer available. You can return to the previous page and refresh to view the latest offer list."
      optional_message: "Or, click here to download %{offer} anyway."
