--- 
ko: 
  activerecord: 
    errors: 
      full_messages: 
        format: "%{attribute} %{message}"
      messages: 
        accepted: "필수동의 사항"
        blank: "필수 입력"
        confirmation: "입력하신 내용이 일치하지 않습니다"
        empty: "필수 입력"
        equal_to: "%{count}와(과) 일치해야 합니다."
        even: "짝수여야 합니다."
        exclusion: "은(는) 사용 중입니다"
        greater_than: "%{count}보다 커야 합니다"
        greater_than_or_equal_to: "%{count}와(과) 같거나 커야 합니다"
        inclusion: "은(는) 목록에 없습니다"
        less_than: "%{count}보다 작아야 합니다"
        less_than_or_equal_to: "%{count}와(과) 같거나 작아야 합니다"
        not_a_number: "은(는) 숫자가 아닙니다"
        not_an_integer: "정수여야만 합니다(소수점은 사용할 수 없습니다)"
        odd: "홀수여야만 합니다"
        record_invalid: "유효하지 않음: %{errors}"
        taken: "은(는) 이미 사용 중입니다"
        too_long: "은(는) 너무 깁니다 (최대 글자수 %{count})"
        too_short: "은(는) 너무 짧습니다 (최소 글자수 %{count})"
        wrong_length: "글자수가 다릅니다(글자수가 %{count}여야 합니다)"
      models: 
        gamer_sessions: 
          attributes: 
            email: Email
            password: Password
      template: 
        body: "다음 필드에 문제가 있습니다:"
        header: 
          one: "한 가지 에러가 있어 저장할 수가 없습니다"
          other: "%{count}개의 에러들이 있어 저장할 수 없습니다"
  authlogic: 
    error_messages: 
      login_not_found: "유효하지 않은 이메일입니다"
      password_invalid: "유효하지 않은 비밀번호입니다"
  errors: 
    format: "%{attribute} %{message}"
    messages: 
      accepted: "필수동의 사항"
      blank: "필수 입력"
      confirmation: "입력하신 내용이 일치하지 않습니다"
      empty: "필수 입력"
      equal_to: "%{count}와(과) 같아야 합니다"
      even: "짝수여야 합니다"
      exclusion: "은(는) 사용 중입니다"
      greater_than: "%{count}보다 커야 합니다"
      greater_than_or_equal_to: "%{count}와(과) 같거나 커야 합니다"
      inclusion: "은(는) 리스트에 포함되어 있지 않습니다"
      less_than: "%{count}보다 작아야만 합니다"
      less_than_or_equal_to: "%{count}와(과) 같거나 작아야 합니다"
      not_a_number: "은(는) 숫자가 아닙니다"
      not_an_integer: "정수여야 합니다(소수점을 사용할 수 없습니다)"
      odd: "홀수여야 합니다"
      too_long: "은(는) 너무 깁니다 (최대 글자수 %{count})"
      too_short: "은(는) 너무 짧습니다 (최소 글자수 %{count})"
      wrong_length: "은(는) 글자수가 다릅니다 (글자수가 %{count}여야 합니다)"
  helpers: 
    select: 
      prompt: "선택해 주세요"
    submit: 
      create: "%{model} 생성"
      submit: "%{model} 저장"
      update: "%{model} 업데이트"
  support: 
    array: 
      last_word_connector: ", 그리고 "
      two_words_connector: " 그리고 "
      words_connector: ", "
    select: 
      prompt: "선택해 주세요"
  text: 
    footer: 
      about: "Tapjoy에 대해"
      advertisers: Advertisers
      blog: Blog
      copyright: "Copyright &copy; %{year} Tapjoy, Inc. All Rights Reserved. Tapjoy and the Tapjoy logo are trademarks or registered trademarks of Tapjoy, Inc. All third party logos and trademarks mentioned are the property of their respective owners."
      developers: Developers
      privacy: "개인정보 보호"
    games: 
      almost_done: "거의 끝났습니다!"
      app_review_concern_reported: "특이사항 리포트"
      app_review_h_no: "아니오"
      app_review_h_yes: "예"
      app_review_more: more...
      app_review_report_concern: "특이사항 리포트"
      app_review_thanks_for_feedback: "피드백을 주셔서 감사합니다"
      app_review_was_helpful: "이 리뷰가 도움이 되셨나요?"
      connected_to_facebook: "페이스북으로 연결"
      connected_to_twitter: "트위터로 연결"
      discover_apps: "지금 바로 Tapjoy에서 수백만의 앱 유저와 함께하고 최고의 평가를 받는 앱들을 만나보세요!"
      download_now: "다운로드"
      email_device_link: "기계링크 이메일 보내기"
      enter_name: "이름을 입력해 주세요"
      errno_error: "연결에 문제가 있습니다. 나중에 다시 시도해 주세요."
      error_mark_as_favorite: "선호 앱에 추가하는데 문제가 발생했습니다"
      error_unmark_as_favorite: "선호 앱에서 제외하는데 문제가 발생했습니다"
      facebook_connect_failed: "당신의 페이스북 프로필로 연결하는데 실패했습니다"
      failed_to_change_linked: "계정 변경에 실패했습니다"
      favorites: Favorites
      find_friends_from_facebook: "페이스북에서 친구찾기"
      find_friends_from_twitter: "트위터에서 친구찾기"
      friend_filter_label: "이름 입력하기"
      grant_permissions_for_invite: "초대 메일 발송 전에 저희에게 두 가지 권한을 부여해주세요."
      install_android_app: "당신의 안드로이드 기기에 Tapjoy앱 다운로드가 시작되었습니다."
      invalid_emails: "이메일이 잘못 입력되었습니다"
      invite_friends: 
        one: Invite
        other: "%{count}명의 친구 초대"
      invite_twitter_followers: "트위터 팔로우 초대!"
      invites_sent_to: 
        one: "탭조이 초대장이 %{name}에게 발송되었습니다"
        other: "탭조이 초대장이 %{name}에게 발송되었습니다"
      link_account_messaging_android_href: "안드로이드 앱 다운로드"
      link_account_messaging_tjm_href: www.tapjoy.com
      mogli_reach_limit_error: "제한에 도달하였습니다. 나중에 다시 시도해 주세요."
      or_learn_more: "또는 더 배우기"
      password_non_match: "입력하신 패스워드가 일치하지 않습니다"
      please_connect_facebook: "당신의 페이스북 계정을 연결해 주세요"
      post_to_facebook: "페이스북에 올리기!"
      profile_error: "당신의 프로필을 업데이트하는데 에러가 발생했습니다."
      provide_single_email: "적어도 하나의 이메일을 입력해 주세요"
      reactivated_account: "당신의 계정이 다시 활성화 되었습니다!"
      recommend_apps: "탭조이는 여러분이 좋아하고 자주 사용하는 앱들을 통해 개별적인 앱 추천을 해드립니다."
      scheduled_for_deletion: "당신의 계정은 비활성화 되었으며, 삭제가 예정되었습니다!"
      social_invite_friend_error: "친구 초대에 문제가 발생하였습니다. 나중에 다시 시도해 주세요."
      social_need_authorize_error: "초대장 발송 전에 권한을 부여해 주세요."
      social_to_next: "다음 %{page_size}"
      social_to_prev: "이전 %{page_size}"
      social_to_top: "최상단 &#8679;"
      spread_mobile_joy: "모바일의 즐거움을 나누세요"
      start_discovering: "무료로 탭조이를 즐겨보세요"
      twitter_at_least_one_friend_error: "초대장 발송 전에 적어도 한 명의 친구가 선택되어야 합니다"
      twitter_authenticate_error: "트위터 인증에 실패하였습니다. 서비스가 유효한 값을 리턴해오지 못했습니다."
      twitter_forbidden_error: "업데이트 제한에 걸려 요청이 거부되었습니다."
      twitter_general_error: "트위터에 무언가 이상이 있습니다. 나중에 다시 시도해 주세요."
      twitter_internal_error: "트위터에 무언가 이상이 있습니다. 나중에 다시 시도해 주세요."
      twitter_invite_msg: "가 당신을 최고로 핫한 앱들을 만날 수 있는 탭조이로 초대하였습니다, 가입은 무료입니다!"
      twitter_invite_title: "트위터 친구를 선택해 메일을 통해 초대해 보세요"
      unmark_as_favorite: "선호에서 삭제하기"
      welcome_tapjoy: "Tapjoy에 오신 것을 환영합니다!"
      you_are_following: "당신은 (%{count}명을 팔로잉 하고 있습니다)"
      your_followers: 
        one: "당신의 팔로워"
        other: "당신의 팔로워 (%{count}명)"
    shared: 
      please_try_again: "다시 시도해 주세요."
      sending: Sending
      sent: Sent
      view_all: "전체 보기"
    unavailable_offer: 
      message: "죄송합니다 %{offer}는 더 이상 이용이 불가능합니다. 이전 페이지로 돌아가거나 페이지를 리프레쉬하여 최신 리스트를 불러와 주세요."
      optional_message: "혹은, 보상이 없어도 괜찮다면 이곳을 클릭해 %{offer}을(를) 다운로드 받으세요."
