--- 
zh: 
  activerecord: 
    errors: 
      full_messages: 
        format: "%{attribute} %{message}"
      messages: 
        accepted: "必須接受"
        blank: "不可以空白"
        confirmation: "與確認內容不匹配"
        empty: "不可以空白"
        equal_to: "必須等於 %{count}"
        even: "必須是偶數"
        exclusion: "被保留了"
        greater_than: "必須大於 %{count}"
        greater_than_or_equal_to: "必須大於或等於 %{count}"
        inclusion: "未包括在本列表中"
        less_than: "必須小於 %{count}"
        less_than_or_equal_to: "必須小於或等於 %{count}"
        not_a_number: "不是個數字"
        not_an_integer: "必須是個整數"
        odd: "必須是奇數"
        record_invalid: "認定失敗: %{errors}"
        taken: "已經被人用了"
        too_long: "̫太長了 (最大長度是 %{count} 字元"
        too_short: "̫太短了 (最小長度是 %{count} 字元)"
        wrong_length: "的長度錯誤 (應該是 %{count} 字元)"
      models: 
        gamer_sessions: 
          attributes: 
            email: Email
            password: Password
      template: 
        body: "以下的欄位有問題"
        header: 
          one: "發生一個讓 %{model} 無法儲存的錯誤"
          other: "發生 %{count}個讓 %{model}無法儲存的錯誤"
  authlogic: 
    error_messages: 
      login_not_found: "無效的電子郵件"
      password_invalid: "無效的密碼"
  errors: 
    format: "%{attribute} %{message}"
    messages: 
      accepted: "必須接受"
      blank: "不可以空白"
      confirmation: "與確認內容不匹配"
      empty: "不可以空白"
      equal_to: "必須等於 %{count}"
      even: "必須是偶數"
      exclusion: "被保留了"
      greater_than: "必須大於 %{count}"
      greater_than_or_equal_to: "必須大於或等於 %{count}"
      inclusion: "未包括在本列表中"
      less_than: "必須小於 %{count}"
      less_than_or_equal_to: "必須小於或等於 %{count}"
      not_a_number: "不是個數字"
      not_an_integer: "必須是個整數"
      odd: "必須是奇數"
      too_long: "太長了 (最大長度是 %{count} 字元)"
      too_short: "太短了 (最小長度是 %{count} 字元)"
      wrong_length: "的長度錯誤 (應該是 %{count} 字元)"
  helpers: 
    select: 
      prompt: "請選擇"
    submit: 
      create: "創造 %{model}"
      submit: "儲存 %{model}"
      update: "更新 %{model}"
  support: 
    array: 
      last_word_connector: ", 與 "
      two_words_connector: " 與 "
      words_connector: ", "
    select: 
      prompt: "請選擇"
  text: 
    footer: 
      about: "關於Tapjoy"
      advertisers: Advertisers
      blog: Blog
      developers: Developers
      privacy: "隱私政策"
    games: 
      app_review_concern_reported: "意見已回報"
      app_review_h_no: "不"
      app_review_h_yes: "是"
      app_review_more: more...
      app_review_report_concern: "回報意見"
      app_review_thanks_for_feedback: "多謝你的反饋"
      app_review_was_helpful: "這個評論有幫助嗎?"
      connected_to_facebook: "連結到Facebook"
      connected_to_twitter: "連結到Twitter"
      discover_apps: "一同加入這個有數百萬行動應用愛好者的Tapjoy園地，來探索評價最好的應用。今天就開始吧!"
      download_now: "正在下載"
      email_device_link: "把聯結發給裝置"
      enter_name: "請輸入姓名"
      errno_error: "發生了聯結問題，請稍候再試。"
      error_mark_as_favorite: "將應用標為最愛時發生錯誤"
      error_unmark_as_favorite: "將應用取消最愛時發生錯誤"
      facebook_connect_failed: "與你Facebook 個人檔案連結時發生錯誤"
      failed_to_change_linked: "切換聯結帳戶時發生錯誤"
      favorites: Favorites
      find_friends_from_facebook: "從Facebook上找朋友"
      find_friends_from_twitter: "從Twitter上找朋友"
      friend_filter_label: "開始輸入姓名"
      grant_permissions_for_invite: "請在送出邀請前授權我們。"
      install_android_app: "在你的Android裝置上下載Tapjoy應用以便開始"
      invalid_emails: "提供的電子郵件無效"
      invite_twitter_followers: "邀請Twitter關注者!"
      link_account_messaging_android_href: "下載Android應用"
      link_account_messaging_tjm_href: www.tapjoy.com
      mogli_reach_limit_error: "你已經到達上限了，請稍後再試"
      or_learn_more: "或者了解更多"
      password_non_match: "密碼與確認內容不匹配"
      please_connect_facebook: "請連結到你的Facebook帳號"
      post_to_facebook: "貼文到Facebook!"
      profile_error: "在更新你的個人檔案時發生問題"
      provide_single_email: "請至少提供一個電子郵件地址"
      reactivated_account: "你的帳號已經被激活了!"
      recommend_apps: "Tapjoy會根據你喜愛使用的應用內容，對你作個人化的智能推薦"
      scheduled_for_deletion: "你的帳號已被關閉並進入刪除排程!"
      social_invite_friend_error: "在邀請你的朋友時發生問題，請稍後再試。"
      social_need_authorize_error: "在送出邀請前，請授權我們"
      social_to_next: "下一頁 %{page_size}"
      social_to_prev: "前一頁 %{page_size}"
      social_to_top: "回頂端 &#8679;"
      spread_mobile_joy: "散布行動娛樂"
      start_discovering: "現在就開始免費與Tapjoy一同探索吧 "
      twitter_at_least_one_friend_error: "在送出邀請前，請至少選擇一名朋友"
      twitter_authenticate_error: "透過TWITTER取得授權時發生錯誤，服務並未傳回有效的資料"
      twitter_forbidden_error: "由於更新限制，要求已經被否決"
      twitter_general_error: "Twitter那邊有點問題，請稍後再試"
      twitter_internal_error: "Twitter那邊有點問題，請稍後再試"
      twitter_invite_msg: "已經邀請你加入Tapjoy，尋找熱門應用的最佳場所，現在就免費加入!"
      twitter_invite_title: "請選擇Twitter朋友，以便用直接訊息邀請他們"
      unmark_as_favorite: "從最愛中移除"
      welcome_tapjoy: "歡迎來到Tapjoy!"
      you_are_following: "你正在關注 (%{count})"
      your_followers: 
        one: "你的關注者"
        other: "你的關注者 (%{count})"
    shared: 
      please_try_again: "請再試一次"
      sending: Sending
      sent: Sent
      view_all: "觀看全部"
    unavailable_offer: 
      message: "很抱歉，但 %{offer} 已經失效了，你可以回到前一頁並更新，來觀看最新的廣告列表"
      optional_message: "或者，還是點擊這裡來下載 %{offer}"

