module QueueNames
  CONVERSION_TRACKING      = RUN_MODE_PREFIX + 'ConversionTracking'
  FAILED_SDB_SAVES         = RUN_MODE_PREFIX + 'FailedSdbSaves'
  FAILED_DOWNLOADS         = RUN_MODE_PREFIX + 'FailedDownloads'
  CLEANUP_WEB_REQUESTS     = RUN_MODE_PREFIX + 'CleanupWebRequests'
  CREATE_OFFERS            = RUN_MODE_PREFIX + 'CreateOffers'
  SEND_MONEY_TXN           = RUN_MODE_PREFIX + 'SendMoneyTxn'
  SEND_CURRENCY            = RUN_MODE_PREFIX + 'SendCurrency'
  APP_STATS                = RUN_MODE_PREFIX + 'AppStats'
  PRE_CREATE_DOMAINS       = RUN_MODE_PREFIX + 'PreCreateDomains'
  CALCULATE_SHOW_RATE      = RUN_MODE_PREFIX + 'CalculateShowRate'
  CLEANUP_STORE_CLICK      = RUN_MODE_PREFIX + 'CleanupStoreClick'
  CALCULATE_NEXT_PAYOUT    = RUN_MODE_PREFIX + 'CalculateNextPayout'
  SELECT_VG_ITEMS          = RUN_MODE_PREFIX + 'SelectVgItems'
  VERIFICATIONS            = RUN_MODE_PREFIX + 'Verifications'
  GET_STORE_INFO           = RUN_MODE_PREFIX + 'GetStoreInfo'
  UPDATE_MONTHLY_ACCOUNT   = RUN_MODE_PREFIX + 'UpdateMonthlyAccount'
end