class BucketNames
  ADIMAGES              = RUN_MODE_PREFIX + 'adimages'
  AD_UDIDS              = RUN_MODE_PREFIX + 'ad-udids'
  CONVERSION_ARCHIVES   = RUN_MODE_PREFIX + 'conversion-archives'
  FAILED_SDB_SAVES      = RUN_MODE_PREFIX + 'failed-sdb-saves'
  FAILED_SQS_WRITES     = RUN_MODE_PREFIX + 'failed-sqs-writes'
  OFFER_DATA            = RUN_MODE_PREFIX + 'offer-data'
  PUBLISHER_ADS         = RUN_MODE_PREFIX + 'publisher-ads'
  SDB_BACKUPS           = RUN_MODE_PREFIX + 'sdb-backups'
  STORE_CLICKS          = RUN_MODE_PREFIX + 'store-clicks'
  STORE_RANKS           = RUN_MODE_PREFIX + 'store-ranks'
  TAPJOY                = RUN_MODE_PREFIX + 'tapjoy'
  VIRTUAL_GOODS         = RUN_MODE_PREFIX + 'virtual_goods'
  WEB_REQUESTS          = RUN_MODE_PREFIX + 'web-requests'
end
