class BucketNames
  ADIMAGES            = RUN_MODE_PREFIX + 'adimages'
  CONVERSION_ARCHIVES = RUN_MODE_PREFIX + 'conversion-archives'
  FAILED_SDB_SAVES    = RUN_MODE_PREFIX + 'failed-sdb-saves-generic'
  FAILED_SQS_WRITES   = RUN_MODE_PREFIX + 'failed-sqs-writes'
  OFFER_DATA          = RUN_MODE_PREFIX + 'offer-data'
  PUBLISHER_ADS       = RUN_MODE_PREFIX + 'publisher-ads'
  SDB_BACKUPS         = RUN_MODE_PREFIX + 'sdb-backups'
  STATS               = RUN_MODE_PREFIX + 'tj-stats'
  STORE_CLICKS        = RUN_MODE_PREFIX + 'store-clicks'
  STORE_RANKS         = RUN_MODE_PREFIX + 'store-ranks'
  TAPJOY              = RUN_MODE_PREFIX + 'tapjoy'
  TAPJOY_GAMES        = RUN_MODE_PREFIX + 'tj-games'
  UDID_REPORTS        = RUN_MODE_PREFIX + 'udid-reports'
  VIRTUAL_GOODS       = RUN_MODE_PREFIX + 'virtual_goods'
  SUPPORT_REQUESTS    = RUN_MODE_PREFIX + 'support-requests'
end
