class QueueNames
  CONVERSION_TRACKING      = RUN_MODE_PREFIX + 'ConversionTracking'
  FAILED_SDB_SAVES         = RUN_MODE_PREFIX + 'FailedSdbSaves'
  FAILED_WEB_REQUEST_SAVES = RUN_MODE_PREFIX + 'FailedWebRequestSaves'
  FAILED_DOWNLOADS         = RUN_MODE_PREFIX + 'FailedDownloads'
  CREATE_CONVERSIONS       = RUN_MODE_PREFIX + 'CreateConversions'
  SEND_CURRENCY            = RUN_MODE_PREFIX + 'SendCurrency'
  APP_STATS_HOURLY         = RUN_MODE_PREFIX + 'AppStatsHourly'
  APP_STATS_DAILY          = RUN_MODE_PREFIX + 'AppStatsDaily'
  PRE_CREATE_DOMAINS       = RUN_MODE_PREFIX + 'PreCreateDomains'
  CALCULATE_SHOW_RATE      = RUN_MODE_PREFIX + 'CalculateShowRate'
  SELECT_VG_ITEMS          = RUN_MODE_PREFIX + 'SelectVgItems'
  GET_STORE_INFO           = RUN_MODE_PREFIX + 'GetStoreInfo'
  UPDATE_MONTHLY_ACCOUNT   = RUN_MODE_PREFIX + 'UpdateMonthlyAccount'
  GRAB_ADVERTISER_UDIDS    = RUN_MODE_PREFIX + 'GrabAdvertiserUdids'
  SDB_BACKUPS              = RUN_MODE_PREFIX + 'SdbBackups'
  MAIL_CHIMP_UPDATES       = RUN_MODE_PREFIX + 'MailChimpUpdates'
  PARTNER_NOTIFICATIONS    = RUN_MODE_PREFIX + 'PartnerNotifications'
  RECOUNT_STATS            = RUN_MODE_PREFIX + 'RecountStats'
  LIMIT_APP_INSTALLS       = RUN_MODE_PREFIX + 'LimitAppInstalls'
  CACHE_OFFERS             = RUN_MODE_PREFIX + 'CacheOffers'
end
