class QueueNames
  CONVERSION_TRACKING      = RUN_MODE_PREFIX + 'ConversionTracking'
  FAILED_SDB_SAVES         = RUN_MODE_PREFIX + 'FailedSdbSaves'
  FAILED_DOWNLOADS         = RUN_MODE_PREFIX + 'FailedDownloads'
  SEND_MONEY_TXN           = RUN_MODE_PREFIX + 'SendMoneyTxn'
  SEND_CURRENCY            = RUN_MODE_PREFIX + 'SendCurrency'
  APP_STATS                = RUN_MODE_PREFIX + 'AppStats'
  PRE_CREATE_DOMAINS       = RUN_MODE_PREFIX + 'PreCreateDomains'
  CALCULATE_SHOW_RATE      = RUN_MODE_PREFIX + 'CalculateShowRate'
  SELECT_VG_ITEMS          = RUN_MODE_PREFIX + 'SelectVgItems'
  GET_STORE_INFO           = RUN_MODE_PREFIX + 'GetStoreInfo'
  UPDATE_MONTHLY_ACCOUNT   = RUN_MODE_PREFIX + 'UpdateMonthlyAccount'
  GRAB_ADVERTISER_UDIDS    = RUN_MODE_PREFIX + 'GrabAdvertiserUdids'
  SDB_BACKUPS              = RUN_MODE_PREFIX + 'SdbBackups'
end
